server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/guli_cart
    username: root
    password: admin
  task:
    execution:
      thread-name-prefix: cart-task-
      pool:
        core-size: 100
        max-size: 500
        keep-alive: 60s
        queue-capacity: 5000
        allow-core-thread-timeout: true
      shutdown:
        await-termination: true
        await-termination-period: 60s
  rabbitmq:
    virtual-host: /bailiang
    host: 192.168.56.10
    username: bailiang
    password: bailiang
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        concurrency: 3
feign:
  sentinel:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
jwt:
  pubKeyPath: E:\IdeaProjects\rsa\rsa.pub
  cookieName: GMALL-TOKEN
  userKey: user-key
  expire: 15552000
