server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com   #需要在nginx配置文件设置，把域名信息放入头信息，然后转发过来
        - id: index-route
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: index-route2
          uri: lb://index-service
          predicates:
            - Host=gmall.com, www.gmall.com
          filters:
            - Auth=/xxx,/yyy,/zzz
        - id: item-route
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
        - id: auth-route
          uri: lb://auth-service
          predicates:
          - Host=sso.gmall.com

jwt:
  pubKeyPath: E:\IdeaProjects\rsa\rsa.pub
  priKeyPath: E:\IdeaProjects\rsa\rsa.pri
  secret: 93rraTU#(!*OI&*a4097odu87.
  expire: 180
  cookieName: GMALL-TOKEN
  nickName: unick